mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('', include('taste.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/taste/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('blog/', views.blog, name="blog"),
    path('contact/', views.contact, name="contact"),
    path('menu/', views.menu, name="menu"),
    path('reservation/', views.reservation, name="reservation"),
    path('chef/', views.chef, name="chef"),
    path('view/<int:pk>/', views.view, name="view"),
    path('our/', views.our, name="our"),
    path('search/', views.search, name="search")
]

mysite/taste/models.py
from django.db import models


class About(models.Model):
    name = models.CharField(max_length=120, blank=False, null=False)
    description = models.TextField(blank=False, null=False)
    image = models.ImageField(upload_to='image/', blank=False, null=False)


class Chef(models.Model):
    name = models.CharField(max_length=120, blank=False, null=False)
    degree = models.CharField(max_length=120, blank=False, null=False)
    description = models.TextField(blank=False, null=False)
    image = models.ImageField(upload_to='image/', blank=False, null=False)
    created_at = models.DateTimeField(auto_now_add=True)


class Orders(models.Model):
    name = models.CharField(max_length=120, blank=False, null=False)
    email = models.EmailField(blank=False, null=False)
    phone = models.CharField(max_length=120, blank=False, null=False)
    check_in = models.CharField(max_length=120, blank=False, null=False)
    time = models.CharField(max_length=120, blank=False, null=False)
    guest = models.CharField(max_length=120, blank=False, null=False)
    created_at = models.DateTimeField(auto_now_add=True)


class Menu(models.Model):
    name = models.CharField(max_length=100, blank=False, null=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    title = models.CharField(max_length=100, blank=False, null=False)
    image = models.ImageField(upload_to='image/', blank=False, null=False)
    price = models.PositiveIntegerField(blank=False, null=False, default=0)
    description = models.TextField(blank=False, null=False)
    menu = models.ForeignKey(Menu, blank=False, null=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True)


class Blog(models.Model):
    name = models.CharField(max_length=120, blank=False, null=False)
    image = models.ImageField(upload_to='image/', blank=False, null=False)
    description = models.TextField(blank=False, null=False)
    a_name = models.CharField(max_length=120, blank=False, null=False)
    a_age = models.PositiveIntegerField(blank=False, null=False, default=0)
    a_image = models.ImageField(upload_to='image/', blank=False, null=False)
    a_description = models.CharField(max_length=120, blank=False, null=False)
    created_at = models.DateTimeField(auto_now_add=True)


class Contact(models.Model):
    name = models.CharField(max_length=120, blank=False, null=False)
    email = models.EmailField(blank=False, null=False)
    subject = models.CharField(max_length=150, blank=False, null=False)
    message = models.TextField(blank=False, null=False)
    created_at = models.DateTimeField(auto_now_add=True)


class Our(models.Model):
    name = models.CharField(max_length=120, blank=False, null=False)
    description = models.TextField(blank=False, null=False)
    image = models.ImageField(upload_to='image/', blank=False, null=False)


class Commit(models.Model):
    name = models.CharField(max_length=120, blank=False, null=False)
    email = models.EmailField(blank=False, null=False)
    website = models.TextField(blank=False, null=False)
    message = models.TextField(blank=False, null=False)
    created_at = models.DateTimeField(auto_now_add=True)

mysite/taste/forms.py
from django import forms
from .models import *


class OrdersForm(forms.ModelForm):
    class Meta:
        model = Orders()
        fields = "__all__"


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact()
        fields = "__all__"


class CommitForm(forms.ModelForm):
    class Meta:
        model = Commit()
        fields = "__all__"


class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu()
        fields = "__all__"


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product()
        fields = "__all__"


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog()
        fields = "__all__"


class ChefForm(forms.ModelForm):
    class Meta:
        model = Chef()
        fields = "__all__"

mysite/taste/views.py
from django.shortcuts import render, redirect
from . import servise
from .models import *
from .forms import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
cont = {
        "phone": "tel://1234567920",
        "address": "198 West 21th Street, Suite 721 New York NY 10016",
        "email": "mailto:info@yoursite.com",
        "website": "https://www.youtube.com/",
        "map": "https://www.google.ru/maps/@41.329482,69.254856,16.74z"
    }


var = [{
    "image1": '../static/fronted/images/bg_6.jpg',
    'image2': '../static/fronted/images/bg_4.jpg',
    'title': 'Perfect Ingredients',
    "desc": f"""Far far away, behind the word mountains, 
    far from the countries Vokalia and Consonantia,
     there live the blind texts. Separated they live 
    in Bookmarksgrove right at the coast of the 
    Semantics, a large language ocean."""
}]


def index(request):
    abouts = servise.get_about()
    blogs = servise.get_blog()
    chefs = servise.get_chef()
    menus = servise.get_menu()
    products = servise.get_product()
    ctx = {
        "hom": "active",
        "blogs": blogs,
        "chefs": chefs,
        "menu": menus,
        "var": var,
        "abouts": abouts,
        "products": products,
    }
    return render(request, 'fronted/taste/index.html', ctx)


def about(request):
    abouts = servise.get_about()
    ctx = {
        "abouts": abouts,
        "abo": "active",
    }
    return render(request, 'fronted/taste/about.html', ctx)


def blog(request):
    blogs = servise.get_blog()
    p = Paginator(blogs, 2)
    page_num = request.GET.get('page', 1)
    total_pages = len(blogs)
    try:
        page = p.page(page_num)
    except PageNotAnInteger:
        page = p.page(1)
    except EmptyPage:
        page = p.page(p.num_pages)

    ctx = {
        "bl": "active",
        "blogs": blogs,
        "page": page,
        "p": p,
        "page_num": page_num,
        "total_pages": total_pages,
        "page_number": page.number

    }
    return render(request, 'fronted/taste/blog.html', ctx)


def chef(request):
    model = Orders()
    form = OrdersForm(request.POST, instance=model)
    if request.POST:
        if form.is_valid():
            form.save()
            return redirect('index')
        else:
            print(form.errors)
    chefs = servise.get_chef()
    ctx = {
        "chr": "active",
        "form": form,
        "chefs": chefs,
    }
    return render(request, 'fronted/taste/chef.html', ctx)


def contact(request):
    model = Contact()
    form = ContactForm(request.POST, instance=model)
    if request.POST:
        if form.is_valid():
            print("AAA")
            form.save()
            print("a")
            return redirect("index")
        else:
            print(form.errors)
    ctx = { 
        "con": "active",
        "form": form,
        "cont": cont,
    }
    return render(request, 'fronted/taste/contact.html', ctx)


def menu(request):
    model = Orders()
    form = OrdersForm(request.POST, instance=model)
    if request.POST:
        if form.is_valid():
            form.save()
            return redirect('index')
        else:
            print(form.errors)
    menus = servise.get_menu()
    products = servise.get_product()
    ctx = {
        "menus": "active",
        "menu": menus,
        "form": form,
        "products": products,
    }
    return render(request, 'fronted/taste/menu.html', ctx)


def reservation(request):
    ctx = {
        "res": "active"
    }
    return render(request, 'fronted/taste/reservation.html', ctx)


def view(request, pk):
    new = servise.get_blog_id(pk)
    blogs = servise.get_blog()
    comments = servise.get_comment()
    model = Commit()
    form = CommitForm(request.POST, instance=model)
    print(55)
    if request.POST:
        print(56)
        print(request.POST)
        if form.is_valid():
            form.save()

            return redirect("our")
        else:
            print(form.errors)
    ctx = {
        "new": new,
        "blogs": blogs,
        "form": form,
        "comments": comments,
    }
    return render(request, 'fronted/taste/blog-single.html', ctx)


def our(request):
    new = servise.get_our()
    blogs = servise.get_blog().order
    comments = servise.get_comment()
    model = Commit()
    form = CommitForm(request.POST, instance=model)
    print(55)
    if request.POST:
        print(56)
        print(request.POST)
        if form.is_valid():
            form.save()

            return redirect("our")
        else:
            print(form.errors)
    ctx = {
        "news": blogs,
        "blogs": blogs,
        "comments": comments,

    }
    return render(request, 'fronted/taste/our.html', ctx)


def search(request):
    news = []
    if request.GET and request.GET.get("search"):
        news = Menu.objects.filter(name__icontains=request.GET.get("search"))
    ctx = {
        "newss": news,
        "search_count": len(news),
        "search_text": request.GET.get("search")
    }
    return render(request, "fronted/taste/search.html", ctx)

mysite/templates/fronted/taste/about.html
{% extends 'fronted/base.html' %}
{% load static %}
{% block content %}
<section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'fronted/images/bg_5.jpg' %});" data-stellar-background-ratio="0.5">
  <div class="overlay"></div>
  <div class="container">
    <div class="row no-gutters slider-text align-items-end justify-content-center">
      <div class="col-md-9 ftco-animate text-center mb-5">
        <h1 class="mb-2 bread">About</h1>
        <p class="breadcrumbs"><span class="mr-2"><a href="index-2.html">Home <i class="fa fa-chevron-right"></i></a></span> <span>About <i class="fa fa-chevron-right"></i></span></p>
      </div>
    </div>
  </div>
</section>

<section class="ftco-section ftco-no-pt ftco-no-pb">
 <div class="container">
  <div class="row d-flex">
    <div class="col-md-6 d-flex">
     <div class="img img-2 w-100 mr-md-2" style="background-image: url({% static 'fronted/images/bg_6.jpg' %});"></div>
     <div class="img img-2 w-100 ml-md-2" style="background-image: url({% static 'fronted/images/bg_4.jpg' %});"></div>
   </div>
   <div class="col-md-6 ftco-animate makereservation p-4 p-md-5">
     <div class="heading-section ftco-animate mb-5">
      <span class="subheading">This is our secrets</span>
      <h2 class="mb-4">Perfect Ingredients</h2>
      <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.
      </p>
      <p><a href="{% url 'our' %}" class="btn btn-primary">Learn more</a></p>
    </div>
  </div>
</div>
</div>
</section>

<section class="ftco-section ftco-counter img" id="section-counter" style="background-image: url({% static 'fronted/images/bg_4.jpg' %});" data-stellar-background-ratio="0.5">
 <div class="container">
  <div class="row d-md-flex align-items-center justify-content-center">
   <div class="col-lg-10">
    <div class="row d-md-flex align-items-center">
      <div class="col-md d-flex justify-content-center counter-wrap ftco-animate">
        <div class="block-18">
          <div class="text">
            <strong class="number" data-number="100">0</strong>
            <span>Tasty Dishes</span>
          </div>
        </div>
      </div>
      <div class="col-md d-flex justify-content-center counter-wrap ftco-animate">
        <div class="block-18">
          <div class="text">
            <strong class="number" data-number="4000">0</strong>
            <span>Dishes Served</span>
          </div>
        </div>
      </div>
      <div class="col-md d-flex justify-content-center counter-wrap ftco-animate">
        <div class="block-18">
          <div class="text">
            <strong class="number" data-number="10">0</strong>
            <span>Restaurants</span>
          </div>
        </div>
      </div>
      <div class="col-md d-flex justify-content-center counter-wrap ftco-animate">
        <div class="block-18">
          <div class="text">
            <strong class="number" data-number="10000">0</strong>
            <span>Happy Customers</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</section>

<section class="ftco-section ftco-no-pt ftco-no-pb ftco-intro bg-primary">
 <div class="container py-5">
  <div class="row py-2">
   <div class="col-md-12 text-center">
    <h2>We Make Delicious &amp; Nutritious Food</h2>
    <a href="{% url 'our' %}" class="btn btn-white btn-outline-white">Book A Table Now</a>
  </div>
</div>
</div>
</section>

<section class="ftco-section testimony-section" style="background-image: url({% static 'fronted/images/bg_5.jpg' %});">
 <div class="overlay"></div>
 <div class="container">
  <div class="row justify-content-center mb-3 pb-2">
    <div class="col-md-7 text-center heading-section heading-section-white ftco-animate">
     <span class="subheading">Testimony</span>
     <h2 class="mb-4">Happy Customer</h2>
   </div>
 </div>
 <div class="row ftco-animate justify-content-center">
  <div class="col-md-7">
    <div class="carousel-testimony owl-carousel ftco-owl">
      {% for about in abouts %}
      <div class="item">
        <div class="testimony-wrap text-center">
          <div class="text p-3">
            <p class="mb-4">{{ about.description}}</p>
            <div class="user-img mb-4" style="background-image: url(/media/{{about.image}})">
             <span class="quote d-flex align-items-center justify-content-center">
               <i class="fa fa-quote-left"></i>
             </span>
           </div>
           <p class="name">{{about.namea}}</p>
           <span class="position">Customer</span>
         </div>
       </div>
     </div>
     {% endfor %}
      </div>
  </div>
 </div>
 </div>
 </section>

{% endblock %}

mysite/templates/fronted/taste/blog-single.html
{% extends 'fronted/base.html' %}
{% load static %}
{% block content %}

<section class="hero-wrap hero-wrap-2" style="background-image: url('{% static 'fronted/images/bg_5.jpg' %}');" data-stellar-background-ratio="0.5">
  <div class="overlay"></div>
  <div class="container">
    <div class="row no-gutters slider-text align-items-end justify-content-center">
      <div class="col-md-9 ftco-animate text-center mb-5">
        <h1 class="mb-2 bread">Blog Single</h1>
        <p class="breadcrumbs"><span class="mr-2"><a href="index-2.html">Home <i class="fa fa-chevron-right"></i></a></span> <span class="mr-2"><a href="blog.html">Blog <i class="fa fa-chevron-right"></i></a></span> <span>Blog Single <i class="fa fa-chevron-right"></i></span></p>
      </div>
    </div>
  </div>
</section>

<section class="ftco-section">
 <div class="container">
  <div class="row">

    <div class="col-lg-8 ftco-animate">
      <h2 class="mb-3">#1. {{new.name}}</h2>
      <p>{{new.description}}</p>
      <p>
        <img src="/media/{{new.image}}" alt="" class="img-fluid">
      <div class="tag-widget post-tag-container mb-5 mt-5">
        <div class="tagcloud">
          <a href="#" class="tag-cloud-link">Food</a>
          <a href="#" class="tag-cloud-link">Wine</a>
          <a href="#" class="tag-cloud-link">Drink</a>
          <a href="#" class="tag-cloud-link">Dish</a>
        </div>
      </div>

      <div class="about-author d-flex p-4 bg-light">
        <div class="bio mr-5">
          <img style="max-width: 60%;height: auto;" src="/media/{{new.a_image}}" alt="Image placeholder" class="img-fluid mb-4">
        </div>
        <div class="desc">
          <h3>{{new.a_name}}</h3>
          <p>{{new.a_description}}</p>
        </div>
      </div>

      <div class="pt-5 mt-5">
        <h3 class="mb-5 h4 font-weight-bold p-4 bg-light">07 Feedbacks</h3>
        <ul class="comment-list">
          {% for com in comments %}
          <li class="comment">
            <div class="vcard bio">
              <img src="{% static 'fronted/images/person_1.jpg' %}" alt="Image placeholder">
            </div>
            <div class="comment-body">
              <h3>{{com.name}}</h3>
              <div class="meta mb-2">{{com.created_at}}</div>
              <p>{{com.message}}</p>
              <p><a href="#" class="reply">Reply</a></p>
            </div>
          </li>
          {% endfor %}
        </ul>
        <!-- END comment-list -->

        <div class="comment-form-wrap pt-5">
          <h3 class="mb-5 h4 font-weight-bold p-4 bg-light">Leave a comment</h3>
          <form action="#" method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="name">Name *</label>
              <input type="text" name="name" class="form-control" id="name">
            </div>
            <div class="form-group">
              <label for="email">Email *</label>
              <input type="email" name="email" class="form-control" id="email">
            </div>
            <div class="form-group">
              <label for="website">Website</label>
              <input type="url" name="website" class="form-control" id="website">
            </div>

            <div class="form-group">
              <label for="message">Message</label>
              <textarea name="message" id="message" cols="30" rows="10" class="form-control"></textarea>
            </div>
            <div class="form-group">
              <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
            </div>

          </form>
        </div>
      </div>
    </div>

    <div class="col-lg-4 sidebar ftco-animate">
      <div class="sidebar-box">
        <form action="{% url 'search' %}" method="get" id="search" class="search-form">
          <div class="form-group">
            <span class="icon icon-search"></span>
            <input type="text" name="search" id="searchName" class="form-control" placeholder="Type a keyword and hit enter">
          </div>
          <button type="submit" class="btn  search_btn_close hidden-xs active"><i class="fa fa-close"></i></button>
        </form>
      </div>
      <div class="sidebar-box ftco-animate">
       <h3>Category</h3>
       <ul class="categories">
        <li><a href="#">Breakfast <span>(6)</span></a></li>
        <li><a href="#">Lunch <span>(8)</span></a></li>
        <li><a href="#">Dinner <span>(2)</span></a></li>
        <li><a href="#">Desserts <span>(2)</span></a></li>
        <li><a href="#">Drinks <span>(2)</span></a></li>
        <li><a href="#">Wine <span>(2)</span></a></li>
      </ul>
    </div>

    <div class="sidebar-box ftco-animate">
      <h3>Popular Articles</h3>
      {% for blog in blogs %}
      <div class="block-21 mb-4 d-flex">
        <a class="blog-img mr-4" style="background-image: url(/media/{{blog.image}});"></a>
        <div class="text">
          <h3 class="heading"><a href="{% static 'view' pk=blog.id %}">{{blog.name}}</a></h3>
          <div class="meta">
            <div><a href="{% static 'view' pk=blog.id %}"><span class="icon-calendar"></span> {{blog.create_data}}</a></div>
            <div><a href="{% static 'view' pk=blog.id %}"><span class="icon-person"></span> {{blog.a_name}}</a></div>
            <div><a href="{% static 'view' pk=blog.id %}"><span class="icon-chat"></span> {{blog.a_age}}</a></div>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>

    <div class="sidebar-box ftco-animate">
      <h3>Tag Cloud</h3>
      <ul class="tagcloud m-0 p-0">
        <a href="#" class="tag-cloud-link">Dish</a>
        <a href="#" class="tag-cloud-link">Food</a>
        <a href="#" class="tag-cloud-link">Lunch</a>
        <a href="#" class="tag-cloud-link">Menu</a>
        <a href="#" class="tag-cloud-link">Dessert</a>
        <a href="#" class="tag-cloud-link">Drinks</a>
        <a href="#" class="tag-cloud-link">Sweets</a>
      </ul>
    </div>

    <div class="sidebar-box ftco-animate">
     <h3>Archives</h3>
     <ul class="categories">
       <li><a href="#">January 2020 <span>(20)</span></a></li>
       <li><a href="#">February 2020 <span>(30)</span></a></li>
       <li><a href="#">March 2020 <span>(20)</span></a></li>
       <li><a href="#">April 2020 <span>(6)</span></a></li>
       <li><a href="#">May 2020 <span>(8)</span></a></li>
     </ul>
   </div>


   <div class="sidebar-box ftco-animate">
    <h3>Paragraph</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
  </div>
</div>
</div>
</div>
</section>

{% endblock %}

mysite/templates/fronted/taste/chef.html
{% extends 'fronted/base.html' %}
{% load static %}
{% block content %}
<section class="hero-wrap hero-wrap-2" style="background-image: url('{% static 'fronted/images/bg_5.jpg' %}');" data-stellar-background-ratio="0.5">
	<div class="overlay"></div>
	<div class="container">
		<div class="row no-gutters slider-text align-items-end justify-content-center">
			<div class="col-md-9 ftco-animate text-center mb-5">
				<h1 class="mb-2 bread">Master Chef</h1>
				<p class="breadcrumbs"><span class="mr-2"><a href="index-2.html">Home <i class="fa fa-chevron-right"></i></a></span> <span>Chef <i class="fa fa-chevron-right"></i></span></p>
			</div>
		</div>
	</div>
</section>
<section class="ftco-section bg-light">
	<div class="container">
		<div class="row justify-content-center mb-5 pb-2">
			<div class="col-md-7 text-center heading-section ftco-animate">
				<span class="subheading">Chef</span>
				<h2 class="mb-4">Our Master Chef</h2>
			</div>
		</div>
		<div class="row">
			{% for chef in chefs %}
			<div class="col-md-6 col-lg-3 ftco-animate">
				<div class="staff">
					<div class="img" style="background-image: url(/media/{{chef.image}});"></div>
					<div class="text px-4 pt-2">
						<h3>{{chef.name}}</h3>
						<span class="position mb-2">{{chef.degree}}</span>
						<div class="faded">
							<p>{{chef.description}}</p>
							<ul class="ftco-social d-flex">
								<li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
								<li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
								<li class="ftco-animate"><a href="#"><span class="icon-google-plus"></span></a></li>
								<li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
</section>
<section class="ftco-section ftco-wrap-about ftco-no-pb ftco-no-pt">
		<div class="container">
			<div class="row no-gutters">
				<div class="col-sm-4 p-4 p-md-5 d-flex align-items-center justify-content-center bg-primary">
					<form method="post">
						{% csrf_token %}
						<h3 class="mb-3">Book your Table</h3>
						<div class="row">
							<div class="col-md-12">
								<div class="form-group">
									<input type="text" name="name" class="form-control" placeholder="Name">
								</div>
							</div>
							<div class="col-md-12">
								<div class="form-group">
									<input type="email" name="email" class="form-control" placeholder="Email">
								</div>
							</div>
							<div class="col-md-12">
								<div class="form-group">
									<input type="text" name="phone" class="form-control" placeholder="Phone">
								</div>
							</div>
							<div class="col-md-12">
								<div class="form-group">
									<div class="input-wrap">
										<div class="icon"><span class="fa fa-calendar"></span></div>
										<input type="text"  name="check_in" class="form-control book_date" placeholder="Check-In">
									</div>
								</div>
							</div>
							<div class="col-md-12">
								<div class="form-group">
									<div class="input-wrap">
										<div class="icon"><span class="fa fa-clock-o"></span></div>
										<input type="text" name="time" class="form-control book_time" placeholder="Time">
									</div>
								</div>
							</div>
							<div class="col-md-12">
								<div class="form-group">
									<div class="form-field">
										<div class="select-wrap">
											<div class="icon"><span class="fa fa-chevron-down"></span></div>
											<select name="guest" id="id_guest" class="form-control">
												<option value="0" >Guest</option>
												<option value="1">1</option>
												<option value="2">2</option>
												<option value="3">3</option>
												<option value="4">4</option>
												<option value="5">5</option>
											</select>
										</div>
									</div>
								</div>
							</div>
							<div class="col-md-12">
								<div class="form-group">
									<input type="submit" value="Book Your Table Now" class="btn btn-white py-3 px-4">
								</div>
							</div>
						</div>
					</form>
						<!-- <a href="https://vimeo.com/45830194" class="icon-video popup-vimeo d-flex justify-content-center align-items-center">
  						<span class="ion-ios-play"></span>
  					</a> -->
  				</div>
  				<div class="col-sm-8 wrap-about py-5 ftco-animate img" style="background-image: url(images/about.jpg);">
  					<div class="row pb-5 pb-md-0">
  						<div class="col-md-12 col-lg-7">
  							<div class="heading-section mt-5 mb-4">
  								<div class="pl-lg-3 ml-md-5">
  									<span class="subheading">About</span>
  									<h2 class="mb-4">Welcome to Taste.it</h2>
  								</div>
  							</div>
  							<div class="pl-lg-3 ml-md-5">
  								<p>On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would have been rewritten a thousand times and everything that was left from its origin would be the word "and" and the Little Blind Text should turn around and return to its own, safe country. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
									<!-- <div class="thumb my-4 d-flex">
			            	<a href="#" class="thumb-menu pr-md-4 text-center">
			            		<div class="img" style="background-image: url(images/lunch-4.jpg);"></div>
			            		<h4>Australian Organic Beef</h4>
			            	</a>
			            	<a href="#" class="thumb-menu pr-md-4 text-center">
			            		<div class="img" style="background-image: url(images/lunch-7.jpg);"></div>
			            		<h4>Australian Organic Beef</h4>
			            	</a>
			            	<a href="#" class="thumb-menu pr-md-4 text-center">
			            		<div class="img" style="background-image: url(images/lunch-6.jpg);"></div>
			            		<h4>Australian Organic Beef</h4>
			            	</a>
			            </div> -->
			          </div>
			        </div>
			      </div>
			    </div>
			  </div>
			</div>
		</section>
{% endblock %}

mysite/templates/fronted/taste/search.html
{% extends 'fronted/base.html' %}
{% load static %}
{% block content%}
<div class="col-xl-8 col-lg-6 col-md-8 main">
				<div class="cat_title">“{{search_text}}” so'ziga doir {{search_count}} ta ma'lumot topildi</div>
				<div class="search_box">
					<form action="{% url 'search' %}" method="get">
						<div class="input-group">
							<input type="text" name="search" placeholder="Поиск">
							<button class="btn submit"><i class="fa fa-search"></i></button>
						</div>
					</form>
				</div>

				<div class="news_box">

						{% for news in new %}

						<div class="cat_news">
							<div class="cat_img"><img src="/media/{{news.image}}" alt=""></div>
							<a href="{% url 'view' pk=news.id %}">{{news.title}}</a>
							<p>{{news.description}}</p>
						</div>
						{% endfor %}
						<nav aria-label="Page navigation">
							<ul class="breadcrumbs">
								<li><a href="#">1</a></li>
								<li><a href="#">2</a></li>
								<li><a href="#">3</a></li>
								<li><a href="#">...</a></li>
								<li><a href="#">6</a></li>
								<li><a href="#">7</a></li>
								<li><a href="#">8</a></li>
							</ul>
						</nav>
					</div>
				</div>
{% endblock %}